jenkinsci/pipeline-stage-view-plugin

ui/src/main/js/view/templates/pipeline-staged.hbs, ui/src/test/resources/view/pipeline_staged/render/03_rest_api_runs_checkpoint_rerun.html, ui/src/test/resources/view/pipeline_staged/render/04_rest_api_runs_failed.html, ui/src/test/resources/view/pipeline_staged/render/07_rest_api_runs_in_progress.html, ui/src/test/resources/view/pipeline_staged/render/expected.html
Perhaps @tfennelly knows what this originally was supposed to be, but anyway I am sick of NetBeans showing this plugin as erroneous because of the bad CSS in the test HTML files!
@reviewbybees
=> colWidths did not seem to exist, leading to malformed HTML/CSS

rest-api/src/main/java/com/cloudbees/workflow/rest/external/ChangeSetExt.java, ui/src/main/js/view/templates/run-changeset.hbs
Resolves [JENKINS-35484](https://issues.jenkins-ci.org/browse/JENKINS-35484). 
Verified manually by changing the property using groovy calls.
=> Property to disable user lookup for changesets for JENKINS-35484

ui/src/main/js/view/pipeline-staged.js
Solves [JENKINS-36384](https://issues.jenkins-ci.org/browse/JENKINS-36384).
@reviewbybees
=> [JENKINS-36384] Fix stage viewport scrolling all the way to the left on re-render with many stages

ui/src/main/js/view/templates/pipeline-staged.less
[JENKINS-37001](https://issues.jenkins-ci.org/browse/JENKINS-37001) fix. 
@reviewbybees
=> [JENKINS-37001] Fix CSS style for UNSTABLE builds

pom.xml, rest-api/pom.xml, ui/pom.xml
What is says on the tin.
Picks up https://github.com/jenkinsci/pipeline-graph-analysis-plugin/pull/5
@reviewbybees
=> Take in final pom versions and bump version for release

ui/src/main/js/view/templates/stage-logs.hbs, ui/src/test/js/view/stage-logs-spec.js
=> Fix test regression with NotExecuted nodes for unreleased change

ui/src/main/js/view/templates/pipeline-staged.hbs, ui/src/main/js/view/templates/pipeline-staged.less, ui/src/test/resources/view/pipeline_staged/render/04_rest_api_runs_failed.html, ui/src/test/resources/view/pipeline_staged/render/07_rest_api_runs_in_progress.html, ui/src/test/resources/view/pipeline_staged/render/08_rest_api_unstable_run.html, ui/src/test/resources/view/pipeline_staged/render/expected.html
@reviewbybees specially @svanoort
=> Empty white space on screens with high resolutions

ui/src/main/js/model/job-history-listener.js, ui/src/test/js/model/job-history-listener-spec.js
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>
=> [FIX JENKINS-34538] Fix duplicated rows when displayName is changed

rest-api/pom.xml, rest-api/src/main/java/com/cloudbees/workflow/rest/external/ChunkVisitor.java, rest-api/src/main/java/com/cloudbees/workflow/rest/external/ErrorExt.java, rest-api/src/test/java/com/cloudbees/workflow/rest/endpoints/JobAndRunAPITest.java
Fixes [JENKINS-38536](https://issues.jenkins-ci.org/browse/JENKINS-38536) in combination with the work in https://github.com/jenkinsci/workflow-api-plugin/pull/33
=> Fix finding the end of the fhinal chunk in the presence of incomplete parallel branches [JENKINS-38536]

ui/src/main/js/view/templates/run-changeset.hbs, ui/src/main/js/view/templates/run-changesets.hbs
It bothers me that I have to repeat the same change in several locations. Any hints on how this can be centralized?
=> Fixed grammar mistake (1 commits -> 1 commit)

rest-api/src/main/java/com/cloudbees/workflow/rest/endpoints/RunAPI.java, rest-api/src/main/java/com/cloudbees/workflow/rest/external/AtomFlowNodeExt.java, rest-api/src/main/java/com/cloudbees/workflow/rest/external/FlowNodeExt.java, rest-api/src/test/java/com/cloudbees/workflow/rest/endpoints/FlowNodeAPITest.java, ui/src/main/js/view/templates/stage-logs.hbs
Reverts jenkinsci/pipeline-stage-view-plugin#61
=> Revert "Link to full node log from the window"

ui/src/main/resources/com/cloudbees/workflow/ui/view/WorkflowStageViewAction/jobMain_zh_CN.properties
See https://github.com/jenkinsci/localization-zh-cn-plugin
=> Migrate into localization-zh-cn-plugin

rest-api/pom.xml
Keeping jackson up-to-date.
cc @olamy
=> Bump jackson2-api version, keep up-to-date.

.mvn/extensions.xml, .mvn/maven.config, pom.xml, rest-api/pom.xml, ui/pom.xml
Signed-off-by: Raihaan Shouhell <raihaan.shouhell@autodesk.com>
=> Incrementalify

rest-api/src/main/java/com/cloudbees/workflow/flownode/FlowNodeUtil.java, rest-api/src/main/java/com/cloudbees/workflow/rest/external/RunExt.java, rest-api/src/main/java/com/cloudbees/workflow/rest/external/StageNodeExt.java, rest-api/src/main/java/com/cloudbees/workflow/rest/external/StatusExt.java, rest-api/src/main/java/com/cloudbees/workflow/util/JSONReadWrite.java, rest-api/src/main/java/com/cloudbees/workflow/util/ModelUtil.java, ui/src/test/java/com/cloudbees/workflow/ui/AbstractPhantomJSTest.java, ui/src/test/java/com/cloudbees/workflow/ui/view/WorkflowStageViewActionTest.java
=> Cleanup unused imports and deprecated code

ui/src/main/js/view/templates/pipeline-staged.less, ui/src/main/js/view/templates/run-changesets.less, ui/src/main/js/view/templates/stage-logs.less, ui/src/main/js/view/widgets/dialog/style.less, ui/src/main/less/stageview_adjunct.less
Fixes https://github.com/jenkinsci/dark-theme-plugin/issues/85
When testing set jenkins.version to be 2.240 and plugin-pom version to be 4.3
<details>
<summary>Main screen - before changes</summary>
</details>
<details>
<summary>Logs pop up - before changes</summary>
</details>
<details>
<summary>Main screen - no theme</summary>
</details>
<details>
<summary>Logs pop up - no theme</summary>
</details>
<details>
<summary>Main screen - Dark theme</summary>
</details>
<details>
<summary>Logs pop up - Dark theme</summary>
</details>
cc @oleg-nenashev @olamy @fqueiruga
=> Add dark theme compatibility

ui/src/main/js/view/templates/stage-logs.less, ui/src/main/js/view/widgets/dialog/style.less
https://issues.jenkins-ci.org/browse/JENKINS-63556
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
=> JENKINS-63556 Fix contrast issues

rest-api/pom.xml, ui/pom.xml
Should fix https://github.com/jenkins-infra/plugin-site/issues/350
=> Fix plugin site GitHub link

rest-api/src/main/java/com/cloudbees/workflow/rest/external/RunExt.java, rest-api/src/test/java/com/cloudbees/workflow/rest/endpoints/ParallelStepTest.java
This solution is offered to resolve the JIRA [JENKINS-63115](https://issues.jenkins-ci.org/browse/JENKINS-63115) that I also created to detail the issue. This solution borrows from the PR #63 from @Nuh which have become stale.
=> Fix Inconsistent Parallel Stage Order

rest-api/src/main/java/com/cloudbees/workflow/flownode/FlowNodeUtil.java, rest-api/src/main/java/com/cloudbees/workflow/rest/AbstractFlowNodeActionHandler.java, rest-api/src/main/java/com/cloudbees/workflow/rest/AbstractWorkflowJobActionHandler.java, rest-api/src/main/java/com/cloudbees/workflow/rest/AbstractWorkflowRunActionHandler.java, rest-api/src/main/java/com/cloudbees/workflow/rest/external/AtomFlowNodeExt.java, rest-api/src/main/java/com/cloudbees/workflow/rest/external/ChunkVisitor.java, rest-api/src/main/java/com/cloudbees/workflow/rest/external/ErrorExt.java, rest-api/src/main/java/com/cloudbees/workflow/rest/external/FlowNodeExt.java, rest-api/src/main/java/com/cloudbees/workflow/rest/external/InputParameterDefExt.java, rest-api/src/main/java/com/cloudbees/workflow/rest/external/StatusExt.java
=> EOL JSR 305

rest-api/src/main/java/com/cloudbees/workflow/rest/external/RunExt.java
avoid get null Result from WorflowRun
=> Fix JENKINS-66453 avoid get null Result from WorkflowRun

ui/src/main/js/view/templates/pipeline-staged.less
- [-] Ensure you have provided tests - that demonstrates feature works or fixes the issue
This is my best guess at implementing https://issues.jenkins.io/browse/JENKINS-65331.
- Duration is hidden behind the progress bar
-- fixed by adding `z-index` (thinking now that 1 is a little high)
- Duration runs off the end of the stage-wrapper (stages with long durations)
-- Fixed by changing the duration to relative positioning
I also changed the `line-height` as changing the positioning stopped the page rendering correctly (the stage-wrappers of different rows started overlapping).
I'm not sure how to add a test for this (as it's a cosmetic change). I tried to compile and run this plugin locally, but the complication failed.
```
[INFO] …
```
=> [JENKINS-65331] Show duration of running steps.

rest-api/src/main/java/com/cloudbees/workflow/rest/endpoints/RunAPI.java
suport fullStages parameter  in rest `GET /job/:job-name/:run-id/wfapi/describe` , for querying one run detail
=> add fullStages param in describe api

rest-api/src/main/java/com/cloudbees/workflow/rest/external/RunExt.java
Running CloudBees CI 2.319.3.4 I found a lot of threads processing Stage View REST requests, including some like
```
"Handling GET /…/job/…/wfapi-checkpoints/ from … : Jetty (winstone)-…" Id=… Group=main RUNNABLE
at java.lang.Throwable.getStackTraceElement(Native Method)
at java.lang.Throwable.getOurStackTrace(Throwable.java:828)
-  locked java.lang.Throwable@…
at java.lang.Throwable.getStackTrace(Throwable.java:817)
at com.google.inject.spi.Elements$RecordingBinder.getElementSource(Elements.java:522)
at com.google.inject.spi.Elements$RecordingBinder.bind(Elements.java:375)
at com.google.inject.spi.Elements$RecordingBinder.bind(Elements.java:381)
at com.google.inject.AbstractModule.bind(AbstractModule.java:101)
at org.jclouds.rest.config.CredentialStoreModule.configure(CredentialStoreModul …
```
=> Optimize check for artifacts

ui/src/main/less/bootstrap-3.2.0/normalize.less
https://github.blog/changelog/2022-04-25-git-io-deprecation/ announces end of life for the git.io service
jenkins-infra/update-center2#588
=> Replace git.io with expanded URLs

ui/package-lock.json, ui/package.json, ui/src/main/java/com/cloudbees/workflow/ui/view/WorkflowStageViewAction.java, ui/src/main/js/view/templates/index.js, ui/src/main/resources/com/cloudbees/workflow/controller.jelly
Inspired by the changes in https://github.com/jenkinsci/pipeline-stage-view-plugin/pull/29
Not sure if there was a way to test this automatically, but I've verified the changes work by locally running.
Fixes https://issues.jenkins.io/browse/JENKINS-35656
=> [JENKINS-35656] Fixes inconsistent timezone display

ui/src/main/less/bootstrap-3.2.0/variables.less
- ~~Ensure you have provided tests - that demonstrates feature works or fixes the issue~~
=> Terminology changes from "master" to "controller"

rest-api/pom.xml
Now, the docs for rest-api plugin point to the  pipeline-stage-view-plugin/README.md in [plugins site](https://plugins.jenkins.io/pipeline-rest-api/).
Actually, it should point to the [rest-api/README.md](https://github.com/jenkinsci/pipeline-stage-view-plugin/blob/master/rest-api/README.md).
=> update url for rest-api

pom.xml
Signed-off-by: Olivier Lamy <olamy@apache.org>
=> fix bom artifact, align with core version

pom.xml, rest-api/src/test/java/com/cloudbees/workflow/flownode/CachingTest.java, rest-api/src/test/java/com/cloudbees/workflow/rest/endpoints/FlowNodeAPITest.java, rest-api/src/test/java/com/cloudbees/workflow/rest/endpoints/InputStepTest.java, rest-api/src/test/java/com/cloudbees/workflow/rest/endpoints/JobAndRunAPITest.java, rest-api/src/test/java/com/cloudbees/workflow/rest/endpoints/ParallelStepTest.java, rest-api/src/test/resources/com/cloudbees/workflow/rest/endpoints/sample-flow.groovy
https://github.com/jenkinsci/pipeline-stage-step-plugin/pull/94
=> Stop testing non-block-scoped `stage`

ui/src/main/js/view/templates/run-input-required.hbs
- [-] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [-] Link to relevant pull requests, esp. upstream and downstream changes
- [-] Ensure you have provided tests - that demonstrates feature works or fixes the issue
=> [JENKINS-69555] Use textarea instead of input for parameter of type TextParameterDefinition

.github/dependabot.yml
Trying to track down a Windows build failure involving `parcel` (#240).
=> Enable NPM updates

LICENSE
Fixed [JIRA ISSUE-75043](https://issues.jenkins.io/browse/JENKINS-75043?jql=resolution%20is%20EMPTY%20and%20component%3D21139)
Added LICENSE File in root directory of repo, referred from pom.xml
=> [JENKINS-75043] Add LICENSE file

ui/src/main/js/view/templates/pipeline-staged.less, ui/src/main/less/stageview.less
Reverts jenkinsci/pipeline-stage-view-plugin#348
=> Revert "Fix pipeline box overflow with scroll"

ui/src/main/js/view/templates/pipeline-staged.hbs, ui/src/test/resources/view/pipeline_staged/render/03_rest_api_runs_checkpoint_rerun.html, ui/src/test/resources/view/pipeline_staged/render/04_rest_api_runs_failed.html, ui/src/test/resources/view/pipeline_staged/render/expected.html
Before:
<kbd><img src="https://github.com/user-attachments/assets/bf738964-65c1-40f7-a2c6-9a50cef2f7fa" /></kbd>
After:
<kbd><img src="https://github.com/user-attachments/assets/db295b99-8434-488f-bd2a-c56f8c12e73b" /></kbd>
=> Fix average times markup

.github/release-drafter.yml
=> Fix release-drafter.yml configuration

ui/src/main/less/stageview.less
Fixed stage-view container overflow on large amount of stages
=> Fix stageview overflow
