- ui/src/main/js/view/stage-logs.js
- ui/src/main/js/view/templates/stage-logs.hbs
- ui/src/main/js/view/templates/stage-logs.less
- ui/src/test/js/view/stage-logs-spec.js
[JENKINS-33110](https://issues.jenkins-ci.org/browse/JENKINS-33110)
@reviewbybees esp. @tfennelly @recena
> [JENKINS-33110] Log details not shown

- pom.xml
- rest-api/pom.xml
- ui/gulpfile.js
- ui/pom.xml
Less-intrusive variant of #7. From CD demo, fixes
```
… org.eclipse.jetty.util.log.JavaUtilLog warn
WARNING: Error while serving …/wfapi/runs
java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:298)
at com.cloudbees.workflow.util.ServeJson$Processor.invoke(ServeJson.java:29)
at …
Caused by: java.lang.NoClassDefFoundError: org/jenkinsci/plugins/workflow/support/steps/input/InputAction
at com.cloudbees.workflow.rest.external.RunExt.isPendingInput(RunE …
```
> Dependency fixes II

- rest-api/src/main/java/com/cloudbees/workflow/rest/external/BuildArtifactExt.java
- ui/src/main/js/util/formatters.js
- ui/src/main/js/view/remove-sidepanel.js
- ui/src/main/less/stageview_adjunct.less
* Solves  [JENKINS-33498](https://issues.jenkins-ci.org/browse/JENKINS-33498) by CSS changes + adding class to the fullscreen view main-panel. 
* Solves [JENKINS-33351](https://issues.jenkins-ci.org/browse/JENKINS-33351) by using relativePath when too many artifacts are set to generate displayPaths (API fix).
* Solve [JENKINS-33714](https://issues.jenkins-ci.org/browse/JENKINS-33714) - Correctly calculate the prefixes for data size
> Grabbag of small fixes

- rest-api/src/main/java/com/cloudbees/workflow/rest/external/FlowNodeExt.java
Integrating with other plugins that need to get a JSON representation of the
pipeline state there is no Stapler request. Currently this throws an NPE which
this fixes.
> Fix flow node links when used with no Stapler request

- ui/src/main/js/view/stage-logs.js
- ui/src/main/js/view/widgets/dialog/index.js
- ui/src/main/js/view/widgets/popover/index.js
- ui/src/test/js/util/formatters-spec.js
This fixes the log window popup placement from [JENKINS-33109](https://issues.jenkins-ci.org/browse/JENKINS-33109) and makes the window placement more natural when users have scrolled down a list of stages.
This places the popup for logs centered at the top of the visible area (a natural placement).  It also adds information about the element triggering the popup (which can be used to modify placement if desired). 
@reviewbybees
> Fix log popup placement [JENKINS-33109]

- pom.xml
- rest-api/src/main/java/com/cloudbees/workflow/util/ServeJson.java
> [JENKINS-34764] Fix PCT against 2.x baseline

- rest-api/src/main/java/com/cloudbees/workflow/rest/external/FlowNodeLogExt.java
- rest-api/src/main/java/com/cloudbees/workflow/rest/external/JobExt.java
- rest-api/src/main/java/com/cloudbees/workflow/rest/external/RunExt.java
- rest-api/src/main/java/com/cloudbees/workflow/rest/external/StageNodeExt.java
- ui/src/main/js/model/runs-stage-grouped.js
Provides java system properties to configure the hardcoded limits on jobs per run, etc per [JENKINS-34791](https://issues.jenkins-ci.org/browse/JENKINS-34791).
> Properties to configure hardcoded limits on APIs - JENKINS-34791

- ui/pom.xml
Fixes the NoSuchAdjunctExceptions with plugin-pom 2.6+ until we can update to the latest plugin parent pom & validate against it.  
Fix to the plugin parent is in PR https://github.com/jenkinsci/plugin-pom/pull/27
@reviewbybees especially @jglick
> Fix the gulp bundle phase so the adjunct is included

- ui/src/main/js/view/templates/pipeline-staged.hbs
Node label uses can't be correctly computed without a block-aware and parallel-aware analysis method. 
We are removing them temporarily per [JENKINS-33290](https://issues.jenkins-ci.org/browse/JENKINS-33290) until a flow analyzer based on the ForkScanner in https://github.com/jenkinsci/workflow-api-plugin/pull/2 and the block-aware analysis APIs in https://github.com/jenkinsci/workflow-api-plugin/pull/6
can be added to replace FlowNodeUtil.
> Remove node labels until they can correctly evaluate blocks with new FlowScanner

- ui/src/main/js/view/templates/index.js
- ui/src/main/js/view/templates/run-input-required.hbs
Easy fix that resolves [JENKINS-36661](https://issues.jenkins-ci.org/browse/JENKINS-36661).  We do escaping on the string and replace all end of line combinations with a \<br\> tag. 
@reviewbybees
> Fix handling of multiline strings for input box prompts [JENKINS-36661]

- rest-api/src/main/java/com/cloudbees/workflow/flownode/FlowNodeUtil.java
- rest-api/src/main/java/com/cloudbees/workflow/rest/endpoints/JobAPI.java
- rest-api/src/main/java/com/cloudbees/workflow/rest/endpoints/flownode/Describe.java
- rest-api/src/main/java/com/cloudbees/workflow/rest/external/JobExt.java
- rest-api/src/main/java/com/cloudbees/workflow/rest/external/RunExt.java
- rest-api/src/test/java/com/cloudbees/workflow/flownode/CachingTest.java
- ui/src/main/js/model/job-history-listener.js
- ui/src/main/js/model/rest-api.js
- ui/src/main/js/model/stage-description.js
* Initially intended to address [JENKINS-36865](https://issues.jenkins-ci.org/browse/JENKINS-36865) by listening for deleted jobs and removing them from the cache.  
* Along the way, also has to implement [JENKINS-34036](https://issues.jenkins-ci.org/browse/JENKINS-34036) 
* In general this should improve serverside and clientside performance a bit, especially on masters with frequent job rename/deletion. 
* Turns out to be *highly* useful as a step towards ripping out the flow scanning algorithm (prep for block-scoped stages support).
In the process of fixing server cache invalidation, the server caching is redone to use the FullItemName of the job & its ID - this allows us to just invalidate *specific* run entries upon delete/rename of jobs, rather than invalidating the whole cache. …
> Redo cache invalidation (bugfix, enhancement, and precursor to new flow scanning)

- rest-api/src/main/java/com/cloudbees/workflow/rest/external/AtomFlowNodeExt.java
- ui/src/main/js/view/templates/stage-logs.hbs
- ui/src/test/js/view/stage-logs-spec.js
Fixes [JENKINS-38133](https://issues.jenkins-ci.org/browse/JENKINS-38133) showing log expand options for steps with no logs, and also adds basic timing info to it.
> Fix  JENKINS-38133 and show timing

- rest-api/pom.xml
- rest-api/src/main/java/com/cloudbees/workflow/rest/external/ChunkVisitor.java
- rest-api/src/test/java/com/cloudbees/workflow/rest/endpoints/FlowNodeAPITest.java
- rest-api/src/test/java/com/cloudbees/workflow/rest/endpoints/JobAndRunAPITest.java
- rest-api/src/test/java/com/cloudbees/workflow/rest/endpoints/ParallelStepTest.java
- ui/src/main/js/view/templates/info-action-popover.less
Fix for [JENKINS-37945](https://issues.jenkins-ci.org/browse/JENKINS-37945)
Tasks:
**Test job:**
```
stage 'sample'
node {
dir('sample') {
dir('more') {
sh 'failme'
}
}
}
```
**Screenshot after fix:**
**Screenshot of legacy stage view (pre-OSSing)**
**Screenshot of stage view 1.7:**
> Fix info popup for stages with errors deeply inside blocks [JENKINS-37945]

- ui/src/main/js/model/job-history-listener.js
Solves [JENKINS-40087](https://issues.jenkins-ci.org/browse/JENKINS-40087) -- root cause is that the "since" parameter to the REST API takes the name of the run ("#3" for example) rather than its id ("3"). 
Thus we were repeatedly fetching all the runs when this was changed by https://github.com/jenkinsci/pipeline-stage-view-plugin/pull/34.
@reviewbybees
> Fix incorrect API call from frontend which fetched all runs even if they were cached [JENKINS-40087]

- pom.xml
- ui/src/main/js/view/templates/run-input-required.hbs
- ui/src/test/js/view/run-input-required-spec.js
- ui/src/test/resources/view/run_input_required/input-model-01.json
Currently there is no way to make a checkbox unchecked by default because of a bug in `run-input-required.hbs`
> [JENKINS-36543] Honor defaultValue=false in BooleanParameterDefinition

- ui/package.json
- ui/pom.xml
Similarly to https://github.com/jenkinsci/pipeline-stage-view-plugin/pull/37/files#r118344817 so see https://github.com/jenkinsci/workflow-cps-plugin/pull/87
Thanks to @jglick  for pointing me at the culprit for the latest failure.
It's possible that some of the frontend plugin dependencies might be removable -- will tinker with that. 
Manually tested to ensure it will still work for users in the wild, not just testing & HPI:run (which handle adjuncts a bit differently).
> Fix build broken by changes to node use in new parent pom

- rest-api/src/main/java/com/cloudbees/workflow/flownode/FlowNodeUtil.java
- rest-api/src/test/java/com/cloudbees/workflow/flownode/CachingTest.java
[JENKINS-38159](https://issues.jenkins-ci.org/browse/JENKINS-38159) - log URLs would have to be rewritten (as well as all HAL links in JSON), so it's better to just purge the cache entry and rebuild when needed.
> Fix broken caching handling of job renames by purging cache entry [JENKINS-38159]

- rest-api/src/main/java/com/cloudbees/workflow/flownode/FlowNodeUtil.java
- rest-api/src/main/java/com/cloudbees/workflow/rest/endpoints/JobAPI.java
- rest-api/src/main/java/com/cloudbees/workflow/rest/endpoints/flownode/Describe.java
- rest-api/src/main/java/com/cloudbees/workflow/rest/external/RunExt.java
- rest-api/src/main/java/com/cloudbees/workflow/rest/hal/Link.java
- rest-api/src/main/java/com/cloudbees/workflow/rest/hal/Links.java
- rest-api/src/test/java/com/cloudbees/workflow/rest/endpoints/JobAndRunAPITest.java
- rest-api/src/test/java/com/cloudbees/workflow/rest/endpoints/UndefinedWorkflowTest.java
Also incidentally fix computation of queue durations (legacy logic was not using run startTime/timestamp like it should, apparently un-noticed because the difference is small).
Run duration (as separate from stage) was not getting the end time directly from the run like it ought to. 
[JENKINS-40162](https://issues.jenkins-ci.org/browse/JENKINS-40162).
> Fix run timing bug for runs [JENKINS-40162]

- rest-api/pom.xml
Fixes [JENKINS-46526](https://issues.jenkins-ci.org/browse/JENKINS-46526) by replacing the Jackson dependency with the Jackson 2 plugin. 
Smoketested, seems to work fine
@reviewbybees
> Fix Jackson2 dependency to use plugin

- ui/src/main/js/view/templates/pipeline-staged.hbs
- ui/src/main/js/view/templates/pipeline-staged.less
- ui/src/test/resources/view/pipeline_staged/render/03_rest_api_runs_checkpoint_rerun.html
- ui/src/test/resources/view/pipeline_staged/render/04_rest_api_runs_failed.html
- ui/src/test/resources/view/pipeline_staged/render/07_rest_api_runs_in_progress.html
- ui/src/test/resources/view/pipeline_staged/render/08_rest_api_unstable_run.html
- ui/src/test/resources/view/pipeline_staged/render/expected.html
Currently, to view a particular build from the pipeline view, you have to find the corresponding job in the build list. To make things more convenient, make the build title link to the build itself, just as each build is in the build list. 
Here is an example how it looks like:
> Make build title link to the build itself

- rest-api/src/main/java/com/cloudbees/workflow/util/ModelUtil.java
Users have noted occasional issues with bogus URLS -- a bogus '/' was being inserted into relative URLs, resulting in '//some/path' which becomes 'https://some/path' rather than 'https://urlBase/some/path'. 
Unfortunately it was not consistently reproducible, so this best-guess change was cut as a hotfix for them to try... and it proves to have resolved the issue. 
The string "CD-418" may be meaningful to some.
> Fix Url Generation Bug With '/' Suffix

- ui/src/main/js/util/formatters.js
We have a stage which doesn't happen...
Declarative: Checkout SCM | SCM clean up (avoid conflicts) | npm install | npm test | npm publish | Results | clean up
-- | -- | -- | -- | -- | -- | --
| 3s | NaNy NaNd | 30s | 40s | 1min 23s | 1s | 2s
It's been like this for a long time, the `NaNy NaNd` is pretty ugly.
> Avoid generating NaNy NaNd

- rest-api/src/main/java/com/cloudbees/workflow/rest/endpoints/RunAPI.java
- rest-api/src/main/java/com/cloudbees/workflow/rest/external/AtomFlowNodeExt.java
- rest-api/src/main/java/com/cloudbees/workflow/rest/external/FlowNodeExt.java
- rest-api/src/test/java/com/cloudbees/workflow/rest/endpoints/FlowNodeAPITest.java
- ui/src/main/js/view/templates/stage-logs.hbs
Switching from the convenient log thing to full log listing is annoying, and in case the logs are longish, often necessary. This adds direct link.
> Link to full node log from the window

- ui/src/main/less/stageview_adjunct.less
Without clear, the pipeline stage-view overlaps the Test Result Trend graph that is floated to the right.
>  Fix overlap when used with Test Result Trend

- ui/src/main/js/view/templates/pipeline-staged.less
- ui/src/main/js/view/widgets/popover/style.less
For moderately long artefact names the popup takes up too much vertical space. To me it makes sense to try and keep longer names on one line. I've also increased the area of the button (no visual change) so the popup is less likely to disappear when a user tries to mouse over it.
This should prevent the list looking like this:
And make it look like this:
> Improve usability of the download artefacts popup 

- rest-api/src/test/java/com/cloudbees/workflow/flownode/CachingTest.java
- rest-api/src/test/java/com/cloudbees/workflow/rest/endpoints/FlowNodeAPITest.java
- rest-api/src/test/java/com/cloudbees/workflow/rest/endpoints/InputStepTest.java
- rest-api/src/test/java/com/cloudbees/workflow/rest/endpoints/JobAndRunAPITest.java
- rest-api/src/test/java/com/cloudbees/workflow/rest/endpoints/ParallelStepTest.java
- ui/src/test/java/com/cloudbees/workflow/ui/view/BuildArtifactsTest.java
- ui/src/test/java/com/cloudbees/workflow/ui/view/FailedJobTest.java
- ui/src/test/java/com/cloudbees/workflow/ui/view/PausedJobTest.java
- ui/src/test/java/com/cloudbees/workflow/ui/view/StagePopupsTest.java
- ui/src/test/java/com/cloudbees/workflow/ui/view/WorkflowStageViewActionTest.java
While looking at the test suite for this plugin, I noticed the `CpsFlowDefinition`s in the tests don't consistently use the script security sandbox. Using the script security sandbox results in a more realistic environment given that the script security sandbox should always be enabled in production.
In this change, I replaced any usages of the deprecated single-argument constructor for `CpsFlowDefinition` with usages of the non-deprecated two-argument constructor, passing in `true` as the second argument in order to always enable the script security sandbox.
> Consistently use sandbox for CpsFlowDefinitions

- ui/src/main/js/util/formatters.js
Number.isNaN() defined in ECMAScript 2015 (6th Edition, ECMA-262), that is not supported by IE11.
To provide compatibility, we have to use isNaN function
https://www.w3schools.com/js/js_versions.asp
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isNaN#Specifications
> use standard isNaN function

- pom.xml
- rest-api/pom.xml
- rest-api/src/main/java/com/cloudbees/workflow/flownode/FlowNodeUtil.java
- rest-api/src/main/java/com/cloudbees/workflow/rest/endpoints/RunAPI.java
- rest-api/src/main/java/com/cloudbees/workflow/rest/external/PendingInputActionsExt.java
- rest-api/src/main/java/com/cloudbees/workflow/rest/external/RunExt.java
- ui/pom.xml
- ui/src/test/resources/view/pipeline_staged/render/03_rest_api_runs_checkpoint_rerun.html
- ui/src/test/resources/view/pipeline_staged/render/04_rest_api_runs_failed.html
- ui/src/test/resources/view/pipeline_staged/render/expected.html
Bumps the [plugin parent POM](https://github.com/jenkinsci/plugin-pom) from 2.22 to 3.48.
See [the changelog](https://github.com/jenkinsci/plugin-pom/blob/master/CHANGELOG.md) and the full diff in [the compare view](https://github.com/jenkinsci/plugin-pom/compare/plugin-2.22...plugin-3.48).
I took this opportunity to modernize the plugin by bumping the minimum Java version to Java 8 and core 2.60.3 or later. This entailed bumping the minimum pipeline plugin dependencies as well, and fixing some callers in the REST API to adapt to the exceptions thrown by newer versions of the Pipeline Input Step plugin.
Also fixed some tests that appear to have been broken by #68.
> Update plugin POM and fix failing tests

- rest-api/src/main/java/com/cloudbees/workflow/flownode/FlowNodeUtil.java
- rest-api/src/main/java/com/cloudbees/workflow/rest/external/RunExt.java
- rest-api/src/main/java/com/cloudbees/workflow/rest/external/StatusExt.java
- rest-api/src/test/java/com/cloudbees/workflow/flownode/CachingTest.java
Signed-off-by: Raihaan Shouhell <raihaan.shouhell@autodesk.com>
Do some sanity checking to ensure that values in the cache are valid and if not invalidate them.
CC: @olamy could you PTAL
> [JENKINS-43556] Add sanity check for cached runs

- rest-api/src/test/java/com/cloudbees/workflow/rest/endpoints/JobAndRunAPITest.java
- ui/src/main/less/stageview_adjunct.less
- ui/src/test/js/helper.js
- ui/src/test/js/view/run-changesets-spec.js
To avoid overlay of stage view over test result and other graphs and to
not display the stage swim lanes on the bottom of the page.
> JENKINS-46096 display the stage view as inline-block

- ui/src/main/js/view/templates/pipeline-staged.less
This makes it possible to see the status of individual stages.
Currently, the CSS for the global pipeline status overrides the status for each individual step. This change only applies the background color to the "start" stage instead of the complete row.
> For JENKINS-58783: Only color stage start with global status

- rest-api/src/main/java/com/cloudbees/workflow/rest/external/ErrorExt.java
- rest-api/src/test/java/com/cloudbees/workflow/rest/external/ErrorExtTest.java
When MissingPropertyException is constructed with the "type" parameter
being "null" (for example restoring a serialized pipeline step with this
exception, but the class isn't available anymore), trying to access the
pipeline stage view will lead to a NullPointerException, because
GROOVY-8936 isn't fixed in the Groovy version shipped with Jenkins.
The problem is fixed in beta versions of Groovy 3.0, but it will probably take a long time for this to arrive in Jenkins. (See https://github.com/apache/groovy/pull/844)
I can provide details on how this happens if someone is interested.
Pinging @jglick since he provided the fix to Groovy
> Workaround for GROOVY-8936 (NPE in Exception)

- ui/src/main/java/com/cloudbees/workflow/ui/view/PluginImpl.java
Fixes https://github.com/jenkinsci/dark-theme/issues/4
cc @oleg-nenashev @olamy 
Before:
After:
> Use icon that is transparent - dark theme compatibility

- rest-api/src/test/java/com/cloudbees/workflow/rest/endpoints/InputStepTest.java
- rest-api/src/test/resources/com/cloudbees/workflow/rest/endpoints/sample-flow.groovy
Because of [JENKINS-63516](https://issues.jenkins-ci.org/browse/JENKINS-63516), password parameters are broken with the input step in Jenkins 2.236 and newer. This test is not specifically related to password parameters, so for now it seems best to just remove the password parameter from the test so it does not fail in the PCT against newer versions of Jenkins.
> [JENKINS-63516] Do not test password parameters with the input step

- ui/src/main/js/view/stage-logs.js
- ui/src/main/js/view/widgets/dialog/index.js
- ui/src/main/less/stageview_adjunct.less
Also set the width to (100%-10px), so this can make better use of the screen real-estate.
Should help address [JENKINS-44470](https://issues.jenkins-ci.org/browse/JENKINS-44470), but could have some more improvements. Similar idea to #41. 
**Screenshots**
<details><summary>Before</summary>
</details>
<details><summary>After</summary>
</details>
`calc` is [supported from IE9](https://developer.mozilla.org/en-US/docs/Web/CSS/calc#Browser_compatibility), so hopefully that's fine. But being in the .less may mean that this works in earlier IE versions, but I haven't tested it.
@ssbarnea, @svanoort are you interested in taking a look?
> Remove JS calculation of width, just use css.

- rest-api/src/main/java/com/cloudbees/workflow/rest/external/ChangeSetExt.java
Ref: https://issues.jenkins-ci.org/browse/JENKINS-63854
There is an important performance issue suffered by instances with a large number of users.
We should disable by default the commit author resolution, because, as far as I know, in the end, the only difference I see is that in the GUI of the stage-view you don’t see the name of the user in Jenkins, but the e-mail address. I have never seen a developer even noticing that the Jenkins administrator disabled this hidden feature which will produce slowness until the user resolution does not happen in an asynchronous mode.
* https://github.com/jenkinsci/pipeline-stage-view-plugin/blob/530ea7ddbcf5a759ed7bf199290411e2c018b9e0/rest-api/src/main/java/com/cloudbees/workflow/rest/external/ChangeSetExt.java#L53
```
java.lang.Thread.State: …
```
> [JENKINS-63854] Disable resolveCommitAuthors from stage-view-plugin by default

- ui/src/main/less/icons.less
This surfaced after #86  / https://github.com/jenkinsci/dark-theme-plugin/issues/4
For `icon-workflow-stage` it's clear that the background image was not intentional. For `icon-git-logo` I'm not 100% sure but it seems that the `icon-git-logo` class is never used so this should be safe to remove.
> Removed unintentional background images

- ui/src/main/less/stageview_adjunct.less
Fix for issue introduced in #107.
I didn't realise I had to escape the calc. Without escaping less will replace it with `calc(90%)`, which is not the same thing.
> Fix calc not being escaped

- ui/src/main/less/bootstrap-3.2.0/variables.less
In the dark theme, the background of the progress bar stays bright. This small fix would solve this problem.
> Fix background of progress bar in dark theme

- rest-api/src/main/java/com/cloudbees/workflow/rest/external/JobExt.java
- rest-api/src/test/java/com/cloudbees/workflow/rest/endpoints/JobAndRunAPITest.java
JobExt.create() used to return maxRunsPerJob + 1 runs instead of
maxRunsPerJob. Moving the check before the addition makes it work if "0"
is set as well.
> Fix counting maxRunsPerJob

- ui/src/main/less/stageview_adjunct.less
This should mean it only affects the larger popup, not the smaller one.
I believe this will fix JENKINS-63892, JENKINS-63914 and JENKINS-63901.
@snago, @TobiX are either of you able to test this with your workflows? I can now see the popup with the `input` stage, but I may have missed something else.
> Move width calculation from .cbwf-widget to .cbwf-widget.cbwf-modal

- ui/src/main/js/view/templates/info-action-popover.less
- ui/src/main/js/view/templates/run-input-required.less
@VirtualTim inspired me to look at some other QoL improvements for this plugin, this time in the input popup. When adding an input with many options, the popup overflows quite early.
Before:
After:
Still fine for small popups:
There are some other nits I have with this popup, but I haven't found good solutions for them yet:
- Closes too fast when mouse leaves the popup
- Opens too the left of the associated stage, but changing that may push the popup out of the browser window to the right if it is used in later stages...
> Allow input popovers to be bigger

- README.md
Fixing README.md to fix changelog to actually point to a place where you can get updated release changelog information. Current link direction has not been updated in years. 
Issue: You click on "See the changelog" at https://plugins.jenkins.io/pipeline-rest-api/#documentation or on your github page and you get directed to a page that is no longer kept up to date.
> Fixing README.md to fix changelog

- ui/src/main/js/view/widgets/dialog/style.less
Scope contrast fix that was added for JENKINS-63556 / #104 down to just the stage log link, allowing URLs in the logs to render as normal
<details>
<summary>Before:</summary>
</details>
<details>
<summary>After:</summary>
</details>
> JENKINS-64015 Fix Job urls are set to the same color as the background in the Pipeline logs

- ui/src/main/js/view/run-input-required.js
- ui/src/main/js/view/widgets/popover/index.js
In #119 I mentioned that I think the input popovers close too fast and now I had some time to search for the cause.
This splits the "open" and "close" delays (were mixed in `inoutDelay` before) - The open delay is now a fixed 250ms (was 500ms before) and the close delay stays at 500ms by default, but the input popover overrides this to 3s - this makes it much more forgiving to select something in the input popover without it accidentally closing on the user.
Maybe 3s is even too long?
> Keep input popovers open for longer

- .github/workflows/maven.yml
- pom.xml
- rest-api/pom.xml
- rest-api/src/main/java/com/cloudbees/workflow/rest/external/FlowNodeLogExt.java
- rest-api/src/test/java/com/cloudbees/workflow/rest/endpoints/ParallelStepTest.java
- rest-api/src/test/java/com/cloudbees/workflow/rest/external/ErrorExtTest.java
- ui/package-lock.json
- ui/pom.xml
* Update parent POM
* Bump Jenkins req to 2.204
* Use BOM
* Remove a broken test (introduced in https://github.com/jenkinsci/pipeline-stage-view-plugin/pull/81/)
* Exclude conflicting servlet-api jar
There is still one failed test with jdk11, can't understand what is going on at this point. Also sems to fail on java 8 after the dependencies update so I think there may be a real issue here.
```
[ERROR] com.cloudbees.workflow.rest.endpoints.ParallelStepTest.test_stages_order  Time elapsed: 2.068 s  <<< FAILURE!
java.lang.AssertionError: expected:<4> but was:<0>
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.failNotEquals(Assert.java:835)
at org.junit.Assert.assertEquals(Assert.java:647)
at org.junit.Assert.assertEquals(Assert.java:633)
at …
```
> Routine updates (prereqs for jdk11 compatibility)

- ui/src/main/java/com/cloudbees/workflow/ui/view/PluginImpl.java
- ui/src/main/resources/com/cloudbees/workflow/ui/view/WorkflowStageViewAction/action.jelly
This PR adds the ability to allow modern Jenkins versions to override PNGs with SVGs where applicable, in favor of core getting a rid of PNG icons in a foreseeable future: jenkinsci/jenkins#5778
Before:
After:
> Let newer Jenkins versions override PNG icons

- ui/src/main/js/view/templates/stage-logs.less
The modal window that can be opened by clicking on the _Logs_ button for some stage can be scrolled, but when reaching the end it will scroll the body as well, which makes it pretty annoying to get to the bottom of the logs quickly (scrolling fast will reach the bottom of the logs and then immediately scroll the modal window away, so you then need to scroll back up).
The `overscroll-behavior: contain;` CSS rule fixes this behavior by preventing the scrolling to go over to the parent when reaching the end (see https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior).
Adding this rule manually through the Chrome webtools in a running Jenkins instance fixes the issue. I did not try to actually compile a local version of Jenkins, as I’m not sure how to do that (I only use Jenkins …
> Prevent scrolling in modal window to scroll the body when reaching the end

- ui/src/main/js/view/templates/pipeline-staged.less
Change introduced in #146 makes times near-unreadable in dark mode. Roll back the change until the regression is resolved.
@timbrown5 @tdspencer3
See https://github.com/jenkinsci/pipeline-stage-view-plugin/pull/146#issuecomment-1029704850
> Revert text-shadow change until dark mode regression is fixed

- rest-api/src/main/java/com/cloudbees/workflow/rest/external/StatusExt.java
Fix valueOf(Throwable t) function
some step(e.x build) failed throw FlowInterruptedException with  actualInterruption is false, so this moment is FAILED status rather than ABORTED
> Fix valueOf(Throwable t) function

- ui/src/main/js/view/templates/pipeline-staged.hbs
After updating everything to the latest versions on our Jenkins instance I noticed that the stage-view no longer appeared if there was a pipeline waiting for input.
The console displayed following error:
`Uncaught Required attribute 'objectUrl' not defined on MVC controller 'run-input-required' element.`
Debugging revealed that the reference in [`/ui/src/main/js/view/templates/pipeline-staged.hbs`](https://github.com/jenkinsci/pipeline-stage-view-plugin/blob/master/ui/src/main/js/view/templates/pipeline-staged.hbs) to fetch the PendingInputAction href was no longer valid:
```js
{{#ifCond this.status '===' 'PAUSED_PENDING_INPUT'}}
<div cbwf-controller="run-input-required" objectUrl="{{../../_links.nextPendingInputAction.href}}"></div>
<div class="status">paused</div>
{{/ifCond}}
```
I'm …
> Fix for: Uncaught Required attribute 'objectUrl' not defined on MVC controller 'run-input-required' element.

- rest-api/src/test/java/com/cloudbees/workflow/Util.java
This library was removed from recent weeklies of Jenkins core. A release of this is needed for plugin compatibility testing (PCT) purposes.
> Stop using Commons HttpClient 3.x in tests

- rest-api/pom.xml
- ui/pom.xml
The old protocol is [deprecated](https://github.blog/2021-09-01-improving-git-protocol-security-github/).
> Use HTTPS SCM URL

- ui/pom.xml
- ui/src/main/js/view/templates/index.js
momentjs is used only for timezone formatting. Replace with Date
> remove momentjs

- ui/pom.xml
Observed the following PCT error when trying to add the `github` plugin to `jenkinsci/bom`:
```
SEVERE: Failed Loading plugin bouncycastle API Plugin v2.27 (bouncycastle-api)
java.io.IOException: Failed to initialize
at hudson.ClassicPluginStrategy.load(ClassicPluginStrategy.java:409)
at hudson.PluginManager$2$1$1.run(PluginManager.java:551)
at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:177)
at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:305)
at jenkins.model.Jenkins$5.runTask(Jenkins.java:1164)
at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:221)
at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:120)
at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
at …
```
> PCT compatibility with GitHub plugin

- pom.xml
This is needed for the forthcoming PCT multi-module mode to pull in the fix for [JENKINS-62658](https://issues.jenkins.io/browse/JENKINS-62658) via https://github.com/jenkinsci/maven-hpi-plugin/pull/453. I tested this successfully with the latest update to the multimodule project branch of PCT, which is now doing `mvn process test-classes` rather than `mvn install`, therefore requiring the fix for [JENKINS-62658](https://issues.jenkins.io/browse/JENKINS-62658). With these changes you can now successfully run `mvn process-test-classes` in the root directory of the repository, which was not possible with the old version of Maven HPI plugin.
CC @car-roll @olamy
> Upgrade plugin parent POM from 4.54 to 4.57

- ui/src/main/resources/com/cloudbees/workflow/controller.jelly
- ui/src/main/resources/com/cloudbees/workflow/controllerScript.js
Maven tests pass and mvn hpi:run does not reveal time zone anymore.
```[tasklist]
```
Converted inline script to recommended approach as mentioned in https://www.jenkins.io/doc/developer/security/csp/#inline-javascript-blocks .
Issue: https://issues.jenkins.io/browse/JENKINS-72137
> feat:Remove inline javascript code from Cloudbees workflow

- rest-api/src/main/java/com/cloudbees/workflow/rest/external/JobExt.java
This REST API method is not used by the stage view GUI, but if anyone did in fact call this endpoint, it would load every build into memory, potentially wrecking controller performance. Forgotten in #14 and I guess earlier & later changes in the same area.
> Cap `runCount` in unused `JobApi.doDescribe`

- pom.xml
- ui/src/main/js/util/ajax.js
- ui/src/main/js/view/run-input-required.js
- ui/src/test/js/helper.js
Now that Prototype.js has been removed in 2.426.x, we can remove the no-longer needed `Object.toJSON` workaround. This PR therefore updates this plugin's baseline to 2.426.3.
> Simplify JSON usages; update baseline to 2.426.3

- ui/src/main/js/view/templates/pipeline-staged.hbs
- ui/src/test/resources/view/pipeline_staged/render/03_rest_api_runs_checkpoint_rerun.html
- ui/src/test/resources/view/pipeline_staged/render/04_rest_api_runs_failed.html
- ui/src/test/resources/view/pipeline_staged/render/07_rest_api_runs_in_progress.html
- ui/src/test/resources/view/pipeline_staged/render/08_rest_api_unstable_run.html
A Run object URL in Jenkins should end with a forward slash. Pipeline stage view run object is not attaching the forward slash - Jenkins has a mechanism to automatically redirect from the non forward slash to with forward slash so it is not a visible problem to the user.
<details><summary>Redirection happening in Jenkins core</summary>
However as we can see it still wastes a network call.
|Description|Screenshot|
|---|---|
|Notice a first request returned with 302, and then the proper request comes with 200|![image](https://github.com/user-attachments/assets/72267c0d-8e1d-457c-b2fb-304df1ebfd94)|
</details>
This issue was found via the CBCI high availability controller we noticed it was flagged for builds currently in execution (these kind of cases are deliberately caught so to fix in the …
> Add the missing forward slash to run relative url

- README.md
- ui/src/main/resources/com/cloudbees/workflow/ui/view/WorkflowStageViewAction/jobMain.jelly
I have some really big jobs and my Jenkins server is running slow. Upon investigation, I noticed that Jenkins spends a lot of time processing API requests from this plugin.
While the Stage View information is very useful, I do not need it to be opened automatically when I open a job. There is a _Full Stage View_ button in the job page that I can click if I want to see it.
This PR allows to disable the automatic opening of the Stage View when a job is opened. This is done by adding a new system property `org.jenkinsci.pipeline.stageview.disabledOnMainJobPage` as `true`. If not set, it behaves as before.
Works great in my local tests.
> Allow to disable Stage View in the main job page through system property
